# test & build & publish when push to the main branch

name: test, build, publish

on:
  push:
    tags:        
      - "v[0-9]\\.[0-9]\\.[0-9]"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: npm ci && npm install
      - name: run tests (vitest)
        run: npm run test
      - name: build
        run: npm run build
      - name: publish
        run: npm publish --access public